### ISSUE TITLE
Should we remove BigQuery from this project?

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-infrastructure-template#38]
We no longer use BQ and there are still lots of references to it in this repo. A file was randomly removed that caused CI to start breaking in https://github.com/cagov/caldata-infrastructure-template/pull/36 so we deleted a couple of references to get CI working again, but there is still stale code mentioning BQ. What to do?

Note to self: pay special care to if/else blocks

**Comment by jkarpen** [comment]
@britt-allen how big of a cleanup job would it be to go through and remove those references? is it a lot of code or just a few places?

**Comment by britt-allen** [comment]
A quick search shows there are 26 results in 9 files so it shoul be fairly small. I can bump the size down to small

<img width="709" alt="Screenshot 2024-08-22 at 12 11 27 PM" src="https://github.com/user-attachments/assets/39af36e7-a00f-48cc-bee7-570717d59fed">

**Comment by britt-allen** [comment]
I wanna discuss with Ian first to see if we want to remove and no longer support it or if we want to fix the issue that was causing CI to break and continue investing in BQ.

**Comment by jkarpen** [comment]
Got it, OK lets keep it in the backlog for now then.

**Comment by jkarpen** [comment]
Adding this to 2024-20 sprint as a reminder to talk to Ian about it when he returns.

**Comment by ian-r-rose** [comment]
I'm in favor of removing it! It will significantly simplify the template. If we ever need to restore it, it will be in the git history
